name: clean_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  get_it:  ^7.6.0
  intl: ^0.18.1
  floor: ^1.4.2



  cupertino_icons: ^1.0.2
  retrofit: ^4.1.0
  flutter_hooks: ^0.20.5
  cached_network_image: ^3.3.1
  dev: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^8.1.2
  floor_generator: ^1.5.0
  build_runner: ^2.4.11

flutter:

  uses-material-design: true